[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient @ ^2.8
    rfetick/ESP32Servo @ ^0.8
    RobTillaart/GY521 @ ^0.5.0
    ESP32Async/ESPAsyncWebServer @ ^3.7.0
    ESP32Async/AsyncTCP @ ^3.3.2

board_build.filesystem = spiffs
